//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> TherapistID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> BookingFTime { get; set; }
        public Nullable<System.DateTime> BookingTTime { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Chekout { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Addressline1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string Status { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> IsPannic { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmergencyName { get; set; }
        public string EmergPhone { get; set; }
        public string Occupation { get; set; }
        public string Employer { get; set; }
        public string FamilyDocor { get; set; }
        public string RefProf { get; set; }
        public string RefSour { get; set; }
        public string ReferredTo { get; set; }
        public string MarkEmail { get; set; }
        public string PatientName { get; set; }
        public string InsuranceComp { get; set; }
        public string PolicyNo { get; set; }
        public string IDNo { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> PlicyDOB { get; set; }
        public string RelPat { get; set; }
        public string AssBen { get; set; }
        public Nullable<bool> IsInvOtherHelthCare { get; set; }
    }
}
