//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocID { get; set; }
        public int RefId { get; set; }
        public int RefType { get; set; }
        public string DocPath { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string DocName { get; set; }
        public string FileContent { get; set; }
        public string MimeType { get; set; }
    }
}
