//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECHBen
    {
        public int ECHBenID { get; set; }
        public string Type { get; set; }
        public string YearlyMax { get; set; }
        public string InitiMax { get; set; }
        public string SubSeqMax { get; set; }
        public string Pay { get; set; }
        public string RefRequired { get; set; }
        public Nullable<long> BookingID { get; set; }
    }
}
