//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBooking
    {
        public int PatientBookingID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> TherapistID { get; set; }
        public string Status { get; set; }
    }
}
