//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapist
    {
        public int TherapistID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmgContName { get; set; }
        public string EmgEmail { get; set; }
        public string EmgPhone { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string AddrLine1 { get; set; }
        public string AddrLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ServiceID { get; set; }
        public string BankDetail { get; set; }
        public string Skill { get; set; }
        public string ServiceArea { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string PostalCode { get; set; }
        public string RegistrationNo { get; set; }
    }
}
